<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>trabajo estadistica 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="estadistica12_files/libs/clipboard/clipboard.min.js"></script>
<script src="estadistica12_files/libs/quarto-html/quarto.js"></script>
<script src="estadistica12_files/libs/quarto-html/popper.min.js"></script>
<script src="estadistica12_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="estadistica12_files/libs/quarto-html/anchor.min.js"></script>
<link href="estadistica12_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="estadistica12_files/libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="estadistica12_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="estadistica12_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="estadistica12_files/libs/bootstrap/bootstrap-1bc8a17f135ab3d594c857e9f48e611b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


<link rel="stylesheet" href="styles.css">
</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">trabajo estadistica 1</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="sexismo-benevolente-y-legitimación-de-la-desigualdad" class="level1">
<h1>Sexismo benevolente y legitimación de la desigualdad</h1>
<p><strong>Introducción</strong></p>
<p>La presente investigación analiza el fenómeno del sexismo en la vida social, poniendo especial atención en sus formas menos evidentes, cotidianas y socialmente aceptadas. Desde esta perspectiva, resulta relevante considerar que no todas estas expresiones se manifiestan de manera explícita o conflictiva; por el contrario, muchas operan a través de prácticas, discursos y normas culturales que contribuyen a la naturalización y legitimación de las diferencias entre hombres y mujeres. En este marco, se considera el sexismo como un fenómeno multidimensional que incluye tanto formas hostiles como benevolentes, las cuales, aunque distintas en su expresión, contribuyen a la reproducción de desigualdades de género.</p>
<p>Para abordar esta temática, resulta necesario delimitar conceptualmente el sexismo y sus alcances. En este sentido, el sexismo se entiende como un conjunto de actitudes, creencias y prácticas que establecen y justifican la desigualdad entre hombres y mujeres, sustentadas en la atribución de características diferenciadas según el género y en la legitimación de jerarquías sociales basadas en dichas diferencias (Glick &amp; Fiske, 1996; Pratto et al., 1994). Asimismo, puede comprenderse como un fenómeno de carácter ambivalente, en tanto integra dos dimensiones: el sexismo hostil, que se expresa mediante actitudes abiertamente negativas hacia las mujeres, y el sexismo benevolente, que consiste en evaluaciones subjetivamente positivas que, sin embargo, refuerzan su subordinación a través de la asignación de roles tradicionales. Ambas dimensiones serán consideradas en el análisis, en tanto permiten captar distintas formas de expresión del prejuicio de género. Por su parte, el prejuicio se entiende como una disposición actitudinal negativa hacia grupos sociales, vinculada a la mantención de jerarquías y desigualdades entre grupos (Pratto et al., 1994; Ho et al., 2012).</p>
<p>A su vez, estas formas de desigualdad pueden ser comprendidas en el marco de la teoría de la dominancia social, la cual plantea que las sociedades humanas tienden a organizarse en sistemas jerárquicos basados en grupos, en los que ciertos grupos mantienen posiciones de poder y privilegio sobre otros, sustentados por ideologías y prácticas que legitiman y reproducen dichas desigualdades (Sidanius &amp; Pratto, 1999).</p>
<p>Desde esta perspectiva, tanto la teoría del sexismo ambivalente como la teoría de la dominancia social permiten comprender cómo distintas formas de prejuicio de género, tanto de carácter hostil como benevolente, pueden contribuir a la legitimación de jerarquías de género. Sin embargo, en contextos donde se promueven ideales de igualdad, la persistencia de estas prácticas plantea una posible tensión entre principios normativos y formas cotidianas de interacción social.</p>
<p>A nivel individual, estas dinámicas estructurales se expresan a través de actitudes y percepciones que contribuyen a la reproducción simbólica de dichas jerarquías, manifestándose en orientaciones como el sexismo y las creencias asociadas a la legitimación de la desigualdad social.</p>
<p>En función de lo anterior, la investigación se orienta a responder la siguiente pregunta:</p>
<p><strong>¿En qué medida las distintas formas de sexismo (benevolente y hostil) se asocian con las orientaciones hacia la dominación social y la legitimación de la desigualdad?</strong></p>
<p>Centrar el análisis en el sexismo como fenómeno multidimensional responde a su capacidad de operar tanto de forma explícita como sutil en la reproducción de desigualdades de género. Mientras el sexismo hostil se manifiesta mediante actitudes abiertamente negativas, el sexismo benevolente se expresa a través de evaluaciones aparentemente positivas que refuerzan roles tradicionales y relaciones de dependencia. En este sentido, ambas dimensiones permiten captar distintas formas en que las jerarquías de género se sostienen en la vida social.</p>
<p>A su vez, estas actitudes pueden ser comprendidas en relación con orientaciones más amplias hacia la dominación social, particularmente a través del concepto de orientación a la dominancia social (SDO), entendido como la tendencia individual a preferir y legitimar relaciones jerárquicas entre grupos (Pratto et al., 1994). Desde esta perspectiva, el sexismo puede interpretarse como una expresión específica de dichas orientaciones, en la medida en que contribuye a la mantención de desigualdades estructurales entre hombres y mujeres.</p>
<p>A partir de ello, se establece como primera línea de análisis la comparación de los niveles de sexismo, tanto benevolente como hostil, según género y edad, con el objetivo de identificar posibles patrones diferenciales en su distribución. Se plantea la siguiente hipótesis:</p>
<p><strong>H1: Los niveles de sexismo, tanto benevolente como hostil, tenderán a ser más elevados en hombres y en personas de mayor edad.</strong></p>
<p>En segundo lugar, resulta pertinente analizar la relación entre el sexismo y las orientaciones hacia la legitimación de la desigualdad, en tanto estas permiten evaluar cómo los individuos interpretan y justifican las jerarquías presentes en la estructura social. En esta investigación, se consideran tres dimensiones analíticas: la dominación grupal, que agrupa actitudes favorables a la jerarquía entre grupos; la meritocracia, que atribuye las diferencias sociales a factores individuales como el esfuerzo y las habilidades; y la oposición a la igualdad, entendida como el rechazo a la igualdad de oportunidades entre grupos. En este marco, se formula la siguiente hipótesis:</p>
<p><strong>H2: El sexismo, tanto benevolente como hostil, se asociará positivamente con la dominación grupal y las creencias meritocráticas, y negativamente con el igualitarismo.</strong></p>
<p>El objetivo general de esta investigación es analizar la relación entre el sexismo, en sus dimensiones benevolente y hostil, y las orientaciones hacia la legitimación de la desigualdad social, así como su variación según características sociodemográficas.</p>
<p><strong>Metodología</strong></p>
<p>El presente estudio utiliza datos de la cuarta ola del Estudio Longitudinal Social de Chile (ELSOC 2019), desarrollado por el Centro de Estudios de Conflicto y Cohesión Social (COES). La población objetivo corresponde a hombres y mujeres entre 18 y 75 años residentes en zonas urbanas del país, y la muestra fue seleccionada mediante un diseño probabilístico, estratificado y multietápico. El tamaño muestral final corresponde aproximadamente a N = 2900 individuos.</p>
<p><strong>Operacionalización de las variables</strong></p>
<p>Para capturar los constructos latentes, se construyeron índices a partir del promedio de ítems (“rowMeans”), previa recodificación de valores perdidos y respuestas no sustantivas. En particular, las categorías “No sabe” y “No responde”, codificadas como -888 y -999 respectivamente en la base de datos, fueron transformadas en valores perdidos (NA) antes de cualquier cálculo, con el fin de evitar sesgos en la estimación.</p>
<p>Asimismo, para asegurar la correcta dirección de las escalas, se procedió a invertir aquellos ítems redactados en sentido igualitario mediante la fórmula (puntuación máxima + 1) - x, garantizando que valores más altos representen consistentemente una mayor presencia del constructo medido. La consistencia interna de cada escala fue evaluada mediante el coeficiente Alfa de Cronbach.</p>
<ul>
<li><p><strong>Sexismo benevolente (VD1):</strong> Se construyó a partir de la batería G01 (ítems g01_1 y g01_2, escala Likert 1–5: 1 = Totalmente en desacuerdo, 5 = Totalmente de acuerdo), que evalúa creencias que idealizan y refuerzan roles tradicionales de género desde una perspectiva aparentemente positiva. Los ítems se mantuvieron en su dirección original, de modo que valores más altos indican mayor nivel de sexismo benevolente. El índice fue calculado como el promedio de los ítems.</p></li>
<li><p><strong>Sexismo hostil (VD2):</strong> Se construyó a partir de la batería G01 (ítems g01_3, g01_4 y g01_5, escala Likert 1–5), que evalúa actitudes abiertamente negativas y conflictivas hacia las mujeres. Los ítems se mantuvieron en su dirección original, de modo que valores más altos indican mayor nivel de sexismo hostil. El índice fue calculado como el promedio de los ítems.</p></li>
<li><p><strong>Dominación grupal (Predictor 1):</strong> Se construyó a partir de la batería C18 (ítems c18_01 y c18_12, escala Likert 1–5: 1 = Totalmente en desacuerdo, 5 = Totalmente de acuerdo), que evalúa actitudes favorables a la jerarquía entre grupos. Los ítems se mantuvieron en su dirección original, de modo que valores más altos indican mayor nivel de legitimación de la desigualdad. El índice fue calculado como el promedio de los ítems.</p></li>
<li><p><strong>Oposición a la igualdad (Predictor 2):</strong> Se construyó a partir de la batería C18 (ítems c18_02 y c18_03, escala Likert 1–5), que evalúa el apoyo a la igualdad de oportunidades entre grupos. Ambos ítems fueron invertidos para asegurar consistencia direccional, de modo que valores más altos en el índice reflejan una mayor oposición a la igualdad y una mayor orientación hacia la desigualdad. El índice fue calculado como el promedio de los ítems.</p></li>
<li><p><strong>Meritocracia (Predictor 3):</strong> Se construyó a partir de la batería C18 (ítems c18_09 y c18_10, escala Likert 1–5), que evalúa la atribución del éxito a factores individuales como el esfuerzo y las habilidades. El ítem c18_13 (“En Chile las personas tienen igualdad de oportunidades para salir adelante”) fue excluido del índice debido a su correlación negativa con el resto de la escala, evidenciada mediante el coeficiente Alfa de Cronbach. Los ítems restantes se mantuvieron en su dirección original, de modo que valores más altos indican mayor adhesión a creencias meritocráticas. El índice fue calculado como el promedio de los ítems.</p></li>
</ul>
<p><strong>Tabla explicativa de variables seleccionadas</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Ítems utilizados</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Sexismo benevolente (VD1)</td>
<td>g01_1, g01_2</td>
</tr>
<tr class="even">
<td>Sexismo hostil (VD2)</td>
<td>g01_3, g01_4, g01_5</td>
</tr>
<tr class="odd">
<td>Dominación grupal</td>
<td>c18_01, c18_12</td>
</tr>
<tr class="even">
<td>Oposición a la igualdad</td>
<td>c18_02, c18_03 (invertidos)</td>
</tr>
<tr class="odd">
<td>Meritocracia</td>
<td>c18_09, c18_10</td>
</tr>
</tbody>
</table>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># librerias, leer base y elegir variables #</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   4.0.1     ✔ tibble    3.2.1
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.0.4     
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (&lt;http://conflicted.r-lib.org/&gt;) to force all conflicts to become errors</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>
Adjuntando el paquete: 'psych'

The following objects are masked from 'package:ggplot2':

    %+%, alpha</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(haven)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>elsoc19 <span class="ot">&lt;-</span> <span class="fu">read_sav</span>(<span class="st">"ELSOC_W04_v2.01.sav"</span>)</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>varelsoc19 <span class="ot">&lt;-</span> elsoc19 <span class="sc">%&gt;%</span> <span class="fu">select</span>(r13_sexo_01, r13_edad_01, g01_01, g01_02, g01_03, g01_04, g01_05,c18_01,c18_12, c18_02, c18_03, c18_09, c18_10, c18_13)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#limpieza casos perdidos, inversion #</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>varelsoc19[varelsoc19 <span class="sc">==</span> <span class="sc">-</span><span class="dv">888</span> <span class="sc">|</span> varelsoc19 <span class="sc">==</span> <span class="sc">-</span><span class="dv">999</span>] <span class="ot">&lt;-</span> <span class="cn">NA</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>varelsoc19 <span class="ot">&lt;-</span> varelsoc19 <span class="sc">%&gt;%</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">c18_02_inv =</span> <span class="dv">6</span> <span class="sc">-</span> c18_02,</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">c18_03_inv =</span> <span class="dv">6</span> <span class="sc">-</span> c18_03</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="section" class="level3">
<h3 class="anchored" data-anchor-id="section"></h3>
<p>Primeramente, comenzaremos analizando el alpha de cronbach de todas nuestros indices construidos, para saber que tan bien estan relacionados entre si los item de una escala, y si realmente estan midiendo lo mismo:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># revision de datos con alfa de cronbach #</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(psych)</span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>alpha_sexismo_b <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(g01_01, g01_02)) <span class="co">#sexismo benevolente</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>alpha_sexismo_b<span class="sc">$</span>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha  G6(smc) average_r    S/N        ase     mean        sd
 0.5204052 0.5293674 0.359959  0.359959 1.1248 0.01601793 3.881148 0.7523017
 median_r
 0.359959</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>alpha_sexismo_h <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(g01_03, g01_04, g01_05)) <span class="co">#sexismo hostil</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a>alpha_sexismo_h<span class="sc">$</span>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha   G6(smc) average_r      S/N        ase     mean        sd
 0.5301443   0.53638 0.4613074 0.2783151 1.156939 0.01408046 3.025923 0.7100954
  median_r
 0.2102199</code></pre>
</div>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Las subescalas de sexismo benevolente (α = .52) y hostil (α = .53) presentaron una consistencia interna moderada, lo que puede atribuirse al reducido número de ítems y a la heterogeneidad conceptual de las afirmaciones incluidas.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>alpha_sdod <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(c18_01, c18_12)) <span class="co"># SDO-D</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>alpha_sdod<span class="sc">$</span>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha   G6(smc) average_r      S/N        ase     mean        sd
 0.6084498 0.6105598 0.4394286 0.4394286 1.567788 0.01330399 2.590347 0.9263842
  median_r
 0.4394286</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>alpha_sdoe <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(c18_02_inv, c18_03_inv)) <span class="co">#SDO-E</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>alpha_sdoe<span class="sc">$</span>total</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha   G6(smc) average_r      S/N         ase     mean
 0.7415709 0.7433566 0.5915415 0.5915415 2.896458 0.008828845 1.747875
        sd  median_r
 0.5817791 0.5915415</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>alpha_meritocracia <span class="ot">&lt;-</span> psych<span class="sc">::</span><span class="fu">alpha</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(c18_09, c18_10 )) <span class="co">#meritocracia</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>alpha_meritocracia<span class="sc">$</span>total </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> raw_alpha std.alpha  G6(smc) average_r      S/N         ase     mean        sd
   0.82057 0.8204244 0.695525  0.695525 4.568684 0.006138202 2.625551 0.9492215
 median_r
 0.695525</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co">#El ítem c18_13 fue excluido del índice de meritocracia debido a su correlación negativa con el resto de la escala, evidenciada mediante el alfa de Cronbach.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="sexismo-alpha-de-crombach" class="level3">
<h3 class="anchored" data-anchor-id="sexismo-alpha-de-crombach">sexismo: alpha de crombach</h3>
<p>Las subescalas de sexismo benevolente (α = .52) y hostil (α = .53) presentaron una consistencia interna moderada, lo que puede atribuirse al reducido número de ítems y a la heterogeneidad conceptual de las afirmaciones incluidas.esto puede indicar una asociación positiva moderada, lo que sugiere que ambos ítems capturan aspectos relacionados del constructo. En este sentido, esto sugiere una asociación moderada entre ellos, indicando que ambos capturan aspectos relacionados del constructo. Por tanto, el índice se considera adecuado para fines exploratorios.</p>
</section>
<section id="alpha-de-crombach" class="level3">
<h3 class="anchored" data-anchor-id="alpha-de-crombach">alpha de crombach:</h3>
<p>dominacion grupal: La escala de dominación grupal presenta una consistencia interna aceptable (α = 0.61), situándose por sobre los valores observados en las escalas de sexismo. Este resultado indica una mayor coherencia entre los ítems que componen el índice, que evidencia que ambos ítems capturan de manera consistente la orientación hacia la jerarquía entre grupos.</p>
<p>En comparación con las escalas de sexismo, este índice presenta una mayor consistencia interna, lo que puede atribuirse a la formulación más homogénea y explícita de los ítems en torno a la jerarquía social.</p>
<p>La escala de oposición a la igualdad presenta una alta consistencia interna (α = 0.74), superando el umbral recomendado de 0.70. Este resultado indica que los ítems que componen el índice están fuertemente correlacionados entre sí y capturan de manera coherente el constructo teórico.</p>
<p>La escala de creencias meritocráticas presenta una alta consistencia interna (α = 0.82), superando ampliamente el umbral recomendado de 0.70. Este resultado indica que los ítems que componen el índice están fuertemente correlacionados y capturan de manera coherente el constructo de meritocracia. La correlación promedio entre los ítems (r = 0.70) evidencia una asociación muy alta, lo que sugiere que ambas variables reflejan de forma consistente la creencia de que el éxito social depende de factores individuales como el esfuerzo y las habilidades. La exclusión del ítem c18_13 permitió mejorar significativamente la consistencia interna del índice, lo que evidencia la importancia de evaluar empíricamente la coherencia de los ítems en la construcción de variables latentes</p>
<p>En conjunto, los resultados muestran que las escalas asociadas a orientaciones ideológicas (meritocracia y oposición a la igualdad) presentan mayores niveles de consistencia interna que las escalas de sexismo, lo que puede atribuirse a una mayor homogeneidad conceptual en sus items.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co">#creacion indices continuos (promedios) #</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>varelsoc19 <span class="ot">&lt;-</span> varelsoc19 <span class="sc">%&gt;%</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">sexismo_b =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., g01_01, g01_02),</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a>    <span class="at">sexismo_h =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., g01_03, g01_04, g01_05),</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb18-13"><a href="#cb18-13" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb18-14"><a href="#cb18-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-15"><a href="#cb18-15" aria-hidden="true" tabindex="-1"></a>    <span class="at">sdo_d =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb18-16"><a href="#cb18-16" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., c18_01, c18_12),</span>
<span id="cb18-17"><a href="#cb18-17" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb18-18"><a href="#cb18-18" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb18-19"><a href="#cb18-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-20"><a href="#cb18-20" aria-hidden="true" tabindex="-1"></a>    <span class="at">sdo_e =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb18-21"><a href="#cb18-21" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., c18_02_inv, c18_03_inv),</span>
<span id="cb18-22"><a href="#cb18-22" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb18-23"><a href="#cb18-23" aria-hidden="true" tabindex="-1"></a>    ),</span>
<span id="cb18-24"><a href="#cb18-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-25"><a href="#cb18-25" aria-hidden="true" tabindex="-1"></a>    <span class="at">meritocracia =</span> <span class="fu">rowMeans</span>(</span>
<span id="cb18-26"><a href="#cb18-26" aria-hidden="true" tabindex="-1"></a>      <span class="fu">select</span>(., c18_09, c18_10),</span>
<span id="cb18-27"><a href="#cb18-27" aria-hidden="true" tabindex="-1"></a>      <span class="at">na.rm =</span> <span class="cn">TRUE</span></span>
<span id="cb18-28"><a href="#cb18-28" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb18-29"><a href="#cb18-29" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb18-30"><a href="#cb18-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb18-31"><a href="#cb18-31" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(varelsoc19 <span class="sc">%&gt;%</span> </span>
<span id="cb18-32"><a href="#cb18-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(sexismo_b, sexismo_h, sdo_d, sdo_e, meritocracia))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   sexismo_b       sexismo_h         sdo_d          sdo_e        meritocracia  
 Min.   :1.000   Min.   :1.000   Min.   :1.00   Min.   :1.000   Min.   :1.000  
 1st Qu.:3.500   1st Qu.:2.667   1st Qu.:2.00   1st Qu.:1.000   1st Qu.:2.000  
 Median :4.000   Median :3.000   Median :2.50   Median :2.000   Median :2.500  
 Mean   :3.881   Mean   :3.026   Mean   :2.59   Mean   :1.748   Mean   :2.626  
 3rd Qu.:4.500   3rd Qu.:3.333   3rd Qu.:3.00   3rd Qu.:2.000   3rd Qu.:3.000  
 Max.   :5.000   Max.   :5.000   Max.   :5.00   Max.   :5.000   Max.   :5.000  
 NA's   :1       NA's   :3       NA's   :19     NA's   :6       NA's   :12     </code></pre>
</div>
</div>
<p>Con el objetivo de describir la distribución de los indices construidos, se calcularon estadísticos descriptivos para las variables continuas. a continuacion el analisis de estos:</p>
<p>En primer lugar, el sexismo benevolente presenta niveles relativamente altos en la muestra (M = 3.88; Md = 4.00), lo que indica una tendencia general a estar de acuerdo con afirmaciones que refuerzan roles tradicionales de género desde una perspectiva aparentemente positiva.</p>
<p>Por su parte, el sexismo hostil muestra niveles más moderados (M = 3.03; Md = 3.00), lo que sugiere una menor adhesión a actitudes abiertamente negativas hacia las mujeres en comparación con el sexismo benevolente.</p>
<p>En relación con la dominación grupal, se observan niveles relativamente bajos (M = 2.59; Md = 2.50), lo que indica una tendencia a rechazar las afirmaciones que justifican jerarquías explícitas entre grupos sociales.</p>
<p>De manera consistente, la oposición a la igualdad presenta niveles bajos (M = 1.75; Md = 2.00), evidenciando una alta adhesión a principios igualitarios en la muestra.</p>
<p>Finalmente, las creencias meritocráticas muestran niveles intermedios (M = 2.63; Md = 2.50), lo que refleja una adhesión moderada a la idea de que el éxito social depende del esfuerzo y las habilidades individuales.</p>
<p>En conjunto, estos resultados sugieren la existencia de una tensión en las actitudes de la muestra: mientras se observa un bajo apoyo a formas explícitas de desigualdad y una alta adhesión a principios igualitarios, persisten niveles relativamente altos de sexismo benevolente y una adhesión moderada a creencias meritocráticas. Esto indica que la legitimación de la desigualdad podría operar de manera más sutil, a través de creencias culturalmente aceptadas y no abiertamente conflictivas.</p>
</section>
<section id="analisis-de-estadisticos" class="level2">
<h2 class="anchored" data-anchor-id="analisis-de-estadisticos">Analisis de estadisticos</h2>
</section>
<section id="h1-los-niveles-de-sexismo-tanto-benevolente-como-hostil-tenderán-a-ser-más-elevados-en-hombres-y-en-personas-de-mayor-edad." class="level2">
<h2 class="anchored" data-anchor-id="h1-los-niveles-de-sexismo-tanto-benevolente-como-hostil-tenderán-a-ser-más-elevados-en-hombres-y-en-personas-de-mayor-edad.">H1: Los niveles de sexismo, tanto benevolente como hostil, tenderán a ser más elevados en hombres y en personas de mayor edad.</h2>
<p>Para evaluar la H1, se realizaron pruebas t de muestras independientes para comparar los niveles de sexismo benevolente y hostil según género. Asimismo, se calcularon correlaciones de Pearson para examinar la relación entre edad y ambas dimensiones del sexismo, para finalmente calcular anova, separando la edad en grupos, y cada uno de estos analizandolos con las variables de sexismo.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co">#para el genero t test, comparar si el sexismo benevolente es difenrente entre hombres y mujeres</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sexismo_b <span class="sc">~</span> r13_sexo_01, <span class="at">data =</span> varelsoc19)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sexismo_b by r13_sexo_01
t = 0.42114, df = 2806.8, p-value = 0.6737
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -0.04071714  0.06299170
sample estimates:
mean in group 1 mean in group 2 
       3.887692        3.876555 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(sexismo_h <span class="sc">~</span> r13_sexo_01, <span class="at">data =</span> varelsoc19)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  sexismo_h by r13_sexo_01
t = 0.54614, df = 2748.2, p-value = 0.585
alternative hypothesis: true difference in means between group 1 and group 2 is not equal to 0
95 percent confidence interval:
 -0.03551174  0.06293044
sample estimates:
mean in group 1 mean in group 2 
       3.034284        3.020574 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co">#correlacion de pearsons para edad continua</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_b, varelsoc19<span class="sc">$</span>r13_edad_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_b and varelsoc19$r13_edad_01
t = 4.7555, df = 3364, p-value = 2.063e-06
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.04806537 0.11518396
sample estimates:
       cor 
0.08171731 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_h, varelsoc19<span class="sc">$</span>r13_edad_01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_h and varelsoc19$r13_edad_01
t = 3.3754, df = 3362, p-value = 0.0007454
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.02436920 0.09173055
sample estimates:
       cor 
0.05811602 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># podriamos usar anova para medir edad por grupos</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>varelsoc19 <span class="ot">&lt;-</span> varelsoc19 <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">edad_grupo =</span> <span class="fu">case_when</span>(</span>
<span id="cb28-6"><a href="#cb28-6" aria-hidden="true" tabindex="-1"></a>      r13_edad_01 <span class="sc">&lt;</span> <span class="dv">30</span> <span class="sc">~</span> <span class="st">"Joven"</span>,</span>
<span id="cb28-7"><a href="#cb28-7" aria-hidden="true" tabindex="-1"></a>      r13_edad_01 <span class="sc">&gt;=</span> <span class="dv">30</span> <span class="sc">&amp;</span> r13_edad_01 <span class="sc">&lt;</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"Adulto"</span>,</span>
<span id="cb28-8"><a href="#cb28-8" aria-hidden="true" tabindex="-1"></a>      r13_edad_01 <span class="sc">&gt;=</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">"Mayor"</span></span>
<span id="cb28-9"><a href="#cb28-9" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb28-10"><a href="#cb28-10" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb28-11"><a href="#cb28-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-12"><a href="#cb28-12" aria-hidden="true" tabindex="-1"></a>anova_b <span class="ot">&lt;-</span> <span class="fu">aov</span>(sexismo_b <span class="sc">~</span> edad_grupo, <span class="at">data =</span> varelsoc19)</span>
<span id="cb28-13"><a href="#cb28-13" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value   Pr(&gt;F)    
edad_grupo     2   16.2   8.102   14.36 6.17e-07 ***
Residuals   3363 1897.6   0.564                     
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
51 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>anova_h <span class="ot">&lt;-</span> <span class="fu">aov</span>(sexismo_h <span class="sc">~</span> edad_grupo, <span class="at">data =</span> varelsoc19)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(anova_h)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>              Df Sum Sq Mean Sq F value  Pr(&gt;F)   
edad_grupo     2    5.4  2.7241   5.418 0.00448 **
Residuals   3361 1690.0  0.5028                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
53 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co">#grafico anova</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(varelsoc19, <span class="fu">aes</span>(<span class="at">x =</span> edad_grupo, <span class="at">y =</span> sexismo_b)) <span class="sc">+</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 row containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="estadistica12_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(varelsoc19, <span class="fu">aes</span>(<span class="at">x =</span> edad_grupo, <span class="at">y =</span> sexismo_h)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 3 rows containing non-finite outside the scale range
(`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="estadistica12_files/figure-html/unnamed-chunk-5-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>se realizo 2 t-test, uno a sexismo benevolente y otro a sexismo hostil para ver como afecta el genero al sexismo.</p>
<p>partiendo por el sexismo benevolente, Los resultados indican que no existen diferencias estadísticamente significativas entre hombres y mujeres (t = 0.42, p = 0.67).</p>
<p>En términos descriptivos, ambos grupos presentan niveles muy similares de sexismo benevolente (M_hombres = 3.89; M_mujeres = 3.88), lo que sugiere que este tipo de actitudes se distribuye de manera homogénea en la población.</p>
<p>En consecuencia, no se encuentra evidencia para apoyar la hipótesis de que los hombres presentan niveles más altos de sexismo benevolente que las mujeres.</p>
<p>pasando al sexismo hostil, la historia se repite. ambos grupos presentan niveles muy similares de sexismo hostil (M_hombres = 3.03; M_mujeres = 3.02), lo que sugiere una distribución homogénea de estas actitudes en la muestra.</p>
<p>En consecuencia, no se encuentra evidencia empírica que respalde la hipótesis de que los hombres presentan mayores niveles de sexismo hostil que las mujeres.</p>
<p>pasando a los resultados de correlacion, Con el fin de analizar la relación entre edad y sexismo benevolente, se estimó una correlación de Pearson. Los resultados muestran una asociación positiva y estadísticamente significativa (r = 0.08, p &lt; 0.001), lo que indica que a mayor edad, tienden a observarse niveles ligeramente más altos de sexismo benevolente.</p>
<p>No obstante, la magnitud de esta correlación es baja, lo que sugiere que, si bien la relación si existe, su intensidad es debil.</p>
<p>ahora pasando a los resultados de Anova, en el caso del sexismo benevolente, Los resultados muestran diferencias estadísticamente significativas entre los grupos etarios (F(2, 3363) = 14.36, p &lt; 0.001), lo que indica que los niveles de sexismo varían en función de la edad. en cambio, a pesar de que con el sexismo hostil los resultados igual indican diferencias estadísticamente significativas entre los grupos (F(2, 3361) = 5.42, p &lt; 0.01), en comparación con el sexismo benevolente, la magnitud de estas diferencias es menor.</p>
<p>Para finalizar, en conjunto, no se observan diferencias significativas de los resultados segun genero, sin embargo, tanto los análisis de correlación como los análisis de varianza evidencian que la edad se asocia significativamente con ambas dimensiones del sexismo. En particular, se observan diferencias entre grupos etarios y una relación positiva entre edad y sexismo, aunque de magnitud baja. Estos hallazgos respaldan parcialmente la hipótesis planteada, confirmando la existencia de variaciones según edad, pero no según género.</p>
</section>
<section id="h2-el-sexismo-tanto-benevolente-como-hostil-se-asociará-positivamente-con-la-dominación-grupal-y-las-creencias-meritocráticas-y-negativamente-con-el-igualitarismo." class="level2">
<h2 class="anchored" data-anchor-id="h2-el-sexismo-tanto-benevolente-como-hostil-se-asociará-positivamente-con-la-dominación-grupal-y-las-creencias-meritocráticas-y-negativamente-con-el-igualitarismo.">H2: El sexismo, tanto benevolente como hostil, se asociará positivamente con la dominación grupal y las creencias meritocráticas, y negativamente con el igualitarismo.</h2>
<p>Para evaluar la H2, se analizaron correlaciones entre ambas dimensiones del sexismo y las orientaciones hacia la legitimación de la desigualdad.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># benevolente</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_b, varelsoc19<span class="sc">$</span>sdo_d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_b and varelsoc19$sdo_d
t = 9.2673, df = 3395, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1241015 0.1897041
sample estimates:
      cor 
0.1570761 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_b, varelsoc19<span class="sc">$</span>meritocracia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_b and varelsoc19$meritocracia
t = 5.6259, df = 3402, p-value = 1.994e-08
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.06261647 0.12918883
sample estimates:
       cor 
0.09601002 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_b, varelsoc19<span class="sc">$</span>sdo_e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_b and varelsoc19$sdo_e
t = -1.4984, df = 3408, p-value = 0.1341
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 -0.059174142  0.007913593
sample estimates:
        cor 
-0.02565917 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># hostil</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_h, varelsoc19<span class="sc">$</span>sdo_d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_h and varelsoc19$sdo_d
t = 19.025, df = 3395, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.2796728 0.3404600
sample estimates:
      cor 
0.3103837 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_h, varelsoc19<span class="sc">$</span>meritocracia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_h and varelsoc19$meritocracia
t = 11.092, df = 3401, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1542216 0.2190787
sample estimates:
      cor 
0.1868537 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor.test</span>(varelsoc19<span class="sc">$</span>sexismo_h, varelsoc19<span class="sc">$</span>sdo_e)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's product-moment correlation

data:  varelsoc19$sexismo_h and varelsoc19$sdo_e
t = 8.6601, df = 3406, p-value &lt; 2.2e-16
alternative hypothesis: true correlation is not equal to 0
95 percent confidence interval:
 0.1137667 0.1794731
sample estimates:
      cor 
0.1467818 </code></pre>
</div>
</div>
<p>para la hipotesis 2, se relaizaron correlaciones de pearsons para analizar como se relacionan las variables con los diferentes tipos de sexismo. partiendo por el sexismo benvolente, su relacion con la variable de dominacion grupal (sdo-d), el valor p nos indica una relacion positiva entre sexismo benevolente y apoyo a dominacion grupal(r = 0.157, p &lt; 0.001). en el caso de la meritocracia, esto se repite, contando con una direccion positiva al igual q el anterior. esto sugiere que el sexismo benevolente no solo se vincula con actitudes explícitas de jerarquía social, sino también con creencias más sutiles que legitiman la desigualdad, como la meritocracia. finalmente, No se observó una correlación estadísticamente significativa entre el sexismo benevolente y la oposición a la igualdad (r = -0.026, p = 0.134), lo que indica que no existe evidencia de una asociación entre ambas variables en la muestra analizada.</p>
<p>En conjunto, los resultados muestran que el sexismo benevolente se asocia positivamente con la dominación grupal y con las creencias meritocráticas, lo que respalda parcialmente la hipótesis planteada. Sin embargo, no se encontró una relación significativa con la oposición a la igualdad, lo que sugiere que esta forma de sexismo no implica necesariamente un rechazo explícito a principios igualitarios, sino que opera a través de mecanismos más sutiles de legitimación de la desigualdad.</p>
<p>Con respecto al sexismo hostil, Se observó una correlación positiva y estadísticamente significativa entre el sexismo hostil y la dominación grupal (r = 0.310, p &lt; 0.001), lo que indica que mayores niveles de actitudes hostiles hacia las mujeres se asocian con un mayor apoyo a la jerarquía entre grupos. Esto, al igual que con sexismo benevolente, se repite con meritocracia,lo que indica que mayores niveles de actitudes hostiles hacia las mujeres se asocian con una mayor adhesión a explicaciones meritocráticas de las diferencias sociales. finalmente, a diferencia con lo ocurrido con el sexismo benevolente, aca la relacion entre sexismo hostil y oposicion a la igualda es positiva, lo que nos dice que Las personas que más apoyan la desigualdad social tienden a mostrar más sexismo hostil, pero la relación es débil.</p>
<p>modelos de regresion:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="co">#benevolente</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>modelo_b <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>  sexismo_b <span class="sc">~</span> r13_sexo_01 <span class="sc">+</span> r13_edad_01 <span class="sc">+</span> sdo_d <span class="sc">+</span> sdo_e <span class="sc">+</span> meritocracia,</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> varelsoc19</span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb48-7"><a href="#cb48-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-8"><a href="#cb48-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_b)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sexismo_b ~ r13_sexo_01 + r13_edad_01 + sdo_d + 
    sdo_e + meritocracia, data = varelsoc19)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.96528 -0.39232  0.09738  0.47428  1.45427 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   3.4286898  0.0780460  43.932  &lt; 2e-16 ***
r13_sexo_01  -0.0188921  0.0264245  -0.715 0.474691    
r13_edad_01   0.0032716  0.0008004   4.088 4.46e-05 ***
sdo_d         0.1257441  0.0144376   8.710  &lt; 2e-16 ***
sdo_e        -0.0839310  0.0227130  -3.695 0.000223 ***
meritocracia  0.0564434  0.0139123   4.057 5.08e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.74 on 3332 degrees of freedom
  (79 observations deleted due to missingness)
Multiple R-squared:  0.03852,   Adjusted R-squared:  0.03708 
F-statistic:  26.7 on 5 and 3332 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co">#hostil: </span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>modelo_h <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  sexismo_h <span class="sc">~</span> r13_sexo_01 <span class="sc">+</span> r13_edad_01 <span class="sc">+</span> sdo_d <span class="sc">+</span> sdo_e <span class="sc">+</span> meritocracia,</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> varelsoc19</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(modelo_h)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = sexismo_h ~ r13_sexo_01 + r13_edad_01 + sdo_d + 
    sdo_e + meritocracia, data = varelsoc19)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2111 -0.4082  0.0566  0.4522  2.1999 

Coefficients:
               Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   2.0346064  0.0703792  28.909  &lt; 2e-16 ***
r13_sexo_01  -0.0038601  0.0238287  -0.162    0.871    
r13_edad_01   0.0017400  0.0007217   2.411    0.016 *  
sdo_d         0.2046550  0.0130193  15.719  &lt; 2e-16 ***
sdo_e         0.0923980  0.0204818   4.511 6.67e-06 ***
meritocracia  0.0857080  0.0125457   6.832 9.94e-12 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.6673 on 3332 degrees of freedom
  (79 observations deleted due to missingness)
Multiple R-squared:  0.1174,    Adjusted R-squared:  0.1161 
F-statistic: 88.63 on 5 and 3332 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>al aplicar el modelo de regresion lineal a el sexismo benevolente, descubrimos que el modelo explica solo un 3.85% de la variabilidad del sexismo benevolente ( R2: 0.0385), lo que nos dice que el fenomeno es mucho mas complejo de lo que pensabamos primeramente. los principales predictores positivos siendo edad (debil pero significativo), meritocracia (moderado) y principalmente dominancia social, siendo el predictor positivo mas fuerte. sexo no es revelante en este caso, y nuestro unico predictor negativo seria oposicion a la igualda (bajo pero significativo).</p>
<p>al aplicar el modelo al sexismo hostil, en cambio, nos da un R2 de 0.117, El modelo explicando un 11.7% de la variabilidad del sexismo hostil. esto es mucho mas alto que el sexismo benevolente, a pesar de seguir siendo bajo, demostrando mas relacion entre las variables ideologicas con este. al igual que la vez anterior, el predictor de genero no es relevante aca, la edad sigue siendo un predictor positivo pero mas bajo que en sexismo benevolente. maritocracia y opsicion a la igualdad son los 2 positivos, y el predictor mas fuerte positivo es dominancia social, igual que en sexismo benevolente</p>
<p>estos resultados nos dicen que el sexismo hostil se asocia de manera consistente con orientaciones ideológicas jerárquicas y antigualitarias, mientras que el sexismo benevolente presenta una estructura más ambivalente, donde distintos componentes de la dominancia social se relacionan en direcciones opuestas. sexismo hosttil y benevolente son 2 tipos muy diferentes de sexismo, que funcionan con logitas distintas, tal como vimos en los distintos resultados. a</p>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>